# Generated by Django 5.2.7 on 2025-11-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(default='MYNAME', max_length=50),
        ),
    ]
